In [1]:
import numpy as np

# Create a sample matrix
X = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Calculate the covariance matrix
covariance_matrix = np.cov(X, rowvar=False)

print(covariance_matrix)


[[9. 9. 9.]
 [9. 9. 9.]
 [9. 9. 9.]]


In [3]:
# Generate a sample from the multivariate normal distribution
mean = 0
std_dev = 1
sample_normal = np.random.normal(mean, std_dev, size=X.shape)

In [4]:
low = 0
high = 1
sample_uniform = np.random.uniform(low, high, size=X.shape)

In [5]:
lam = 1
sample_exponential = np.random.exponential(lam, size=X.shape)

# Generate a sample from the Poisson distribution
lam = 1
sample_poisson = np.random.poisson(lam, size=X.shape)

In [6]:

print(sample_normal)
print(sample_uniform)
print(sample_exponential)
print(sample_poisson)

[[-0.84488697  1.06930797  0.13571797]
 [ 0.46261119  0.97073091  0.63785754]
 [ 0.02840411 -1.32743153  0.31199868]]
[[0.27748392 0.61203959 0.99988999]
 [0.85785944 0.40831982 0.86994687]
 [0.63886735 0.59473939 0.74558343]]
[[0.59196906 0.5386319  0.24305325]
 [0.436739   0.11819263 2.54021747]
 [0.09447237 1.99231794 2.62121341]]
[[2 0 0]
 [1 2 1]
 [1 1 1]]
